version: '3.8'

services:
  nuxt-app:
    build: .
    container_name: nuxt_preview
    networks:
      - scoobydoo
    environment:
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - DATA_DIR=/app/data
    volumes:
      - ./data:/app/data
      - ./uploads:/app/public/uploads
    restart: unless-stopped

networks:
  scoobydoo:
    external: true
